### ISSUE TITLE
Unable to add an sql expression to the condition.

### ISSUE THREAD

**Issue by Oioio** [PHPixie/ORM#10]
....
$expression = $database->sqlExpression("json_extract_path_text(data, 'somefield')");
$query->andWhere($expression, 'somevalue');
$query->find();

Warning: strpos() expects parameter 1 to be string, object given in https://github.com/PHPixie/ORM/blob/master/src/PHPixie/ORM/Conditions/Builder/Container.php#L25

**Comment by dracony** [comment]
I see. Currently sql expressions have only been supported for values, e.g:

$query->where('somefield', $expression);

The problem with supporting them for field names is that in many cases
field names get prefixed with table aliases when running a query.

Sure, I'll find a way to implement expressions for fields.

In the meantime lets find a temporary workaround for you. Can you give me
an example of what query you are trying to execute ?

**Comment by Oioio** [comment]
Thanks, but I already solved the problem for my case.
