### ISSUE TITLE
Proper commit messages

### ISSUE THREAD

**Issue by harikt** [PHPixie/ORM#8]
A proper commit message will be nice to read than just "doing" .

Thanks!

**Comment by dracony** [comment]
@harikt Now that it's done would you suggest squashing commits into larger parts and giving them proper messages ?

**Comment by harikt** [comment]
@dracony as you wish. I will close this issue .

Thanks!

**Comment by harikt** [comment]
Hi @dracony , 

one request . If you can, could you add proper messages to commits, so watching the repo will make sense :) .

Thank you.
